version: "3.3" 
services:
  gateway:
    image: gateway 
    build:
      context: gateway
    volumes:
      - type: bind
        source: ./config
        target: /root/config
    environment:
      WG_NAME:
      WG_COUNT:
      WG_NETWORK:
      WG_PORT:
      SSH_KEY:
      VULTR_API_KEY:
      TF_VAR_HOSTNAME:
      TF_VAR_REGION_ID:
      TF_VAR_PLAN_ID:
      TF_VAR_OS_ID:
