#!/bin/bash
SSH_KEY=/root/config/${WG_HOSTNAME}-key
if [ -e ${SSH_KEY} ]; then
  echo "Generating ssh key:
  ssh-keygen -t ed25519 -f ${SSH_KEY} -N ""
else
  echo "Using existing ssh key:
fi
ls -al $SSH_KEY
