version: "3.3"

services:
  wireguard:
    image: wireguard-$NAME
    build:
      context: wireguard
    restart: unless-stopped
    environment:
      NAME:
    ports:
      - "$PORT:$PORT/udp"
    volumes:
      - /lib/modules:/lib/modules
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    sysctls:
    - net.ipv4.ip_forward=1
