#!/bin/bash

set -e
set -o pipefail

exec 2>&1

NAME=$(cat env/NAME)
HEADER="[wireguard-$NAME]"

echo "$HEADER Startup"

cleanup () {
  echo "$HEADER Cleanup"
  docker-compose down
  docker system prune --force
}

trap cleanup EXIT

reaper() {
  echo "$HEADER Received signal"
  exit
}

trap reaper HUP INT QUIT TERM 

status() {
	docker-compose exec wireguard wg status
}
trap status ALRM

# full container rebuild
if [ -f ./rebuild ]; then
  docker system prune --force
  envdir env docker-compose build --no-cache
  rm ./rebuild
fi

# run until stopped
(envdir env docker-compose up)&
wait

echo "$HEADER process exited"
